### ISSUE TITLE
Abbellire il programma con animazioni

### ISSUE THREAD

**Issue by prahtz** [Wadaboa/Holum-Project#1]
Per abbellire alcune parti del programma (come quando si apre il menu o come quando appaiono i video) andrebbero aggiunte alcune animazioni. Un' idea sarebbe, prendendo spunto dall'apertura delle applicazioni su **Android**, quella di far apparire gli oggetti da visualizzare a una velocità costante dal basso verso il centro. Se non avete capito un cazzo provate ad aprire un'app sul telefono. Se ancora non avete capito andate _a fare in culo_. Fatemi sapere chi vuole fare questa parte.

**Comment by Wadaboa** [comment]
@sodiniss

**Comment by Wadaboa** [comment]
4111f162caee19263ffa73ed7ad054673933463b Introdotte animazioni nella classe Menu.

**Comment by prahtz** [comment]
Mancano quelle dei video @sodiniss

**Comment by prahtz** [comment]
e69fd55709ed7cc6fe1234d589a384dd1dfbefaa Animazioni completate
