### ISSUE TITLE
Dinamicità delle animazioni

### ISSUE THREAD

**Issue by Wadaboa** [Wadaboa/Holum-Project#6]
Scrivere una funzione generale per la rappresentazione delle animazioni, sia nella classe Menu che nella classe Video. Questa funzione deve consentire il passaggio di un parametro per l'identificazione dell'animazione da svolgere e spostare dinamicamente gli oggetti presenti nella GUI.

**Comment by prahtz** [comment]
11f4812e5197c7a91ee1af1cb42de0b5c40eb636 animazione dinamica implementata per la classe Menu.
